import { createUseStyles } from 'react-jss';

export const useStyles = createUseStyles({
  container: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    padding: '20px',
    maxWidth: '1200px',
    margin: '0 auto',
    gap: '20px',
  },
  productContainer: {
    flex: 2,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent:'space-between',
    padding: '20px',
    border: '1px solid #ddd',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
  },
  productTitle: {
    fontSize: '2rem',
    fontWeight: 'bold',
    color: '#333',
    marginBottom: '10px',
  },
  productImage: {
    width: '100%',
    maxWidth: '250px',
    height: 'auto',
    objectFit: 'cover',
    borderRadius: '8px',
    margin: '20px 0',
  },
  productDescription: {
    fontSize: '1rem',
    color: '#555',
    marginBottom: '20px',
    lineHeight: '1.5',
  },
  additionalDescription: {
    fontSize: '0.9rem',
    color: '#777',
    marginBottom: '20px',
    lineHeight: '1.4',
  },
  productPrice: {
    fontSize: '1.2rem',
    color: '#333',
    fontWeight: 'bold',
    marginBottom: '20px',
  },
  quantityContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '20px',
  },
  quantityButton: {
    padding: '5px 10px',
    fontSize: '1rem',
    border: '1px solid #333',
    borderRadius: '4px',
    backgroundColor: '#f9f9f9',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#ddd',
    },
  },
  basketContainer: {
    flex: 1,
    position: 'sticky',
    top: '20px', // Keeps the basket fixed when scrolling
    alignSelf: 'flex-start',
    width: '100%',
    maxWidth: '300px',
    padding: '20px',
    border: '1px solid #ddd',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    backgroundColor: '#fff',
  },
  basketButton: {
    backgroundColor: '#008CBA',
    color: '#fff',
    padding: '10px 20px',
    fontSize: '1rem',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    width: '100%',
    transition: 'background-color 0.3s ease',
    '&:hover': {
      backgroundColor: '#005f75',
    },
  },
});
